# Generated by Django 4.2.30 on 2026-06-14 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
